
name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: |
        cd linked_list_exercises
        cargo build --all --verbose

    - name: Run tests
      run: |
        cd linked_list_exercises
        cargo test --all --verbose

